{{- if eq (include "app.storageSecretEnabled" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  azurestorageaccountname: {{ include "app.storageAccountName" . | quote }}
  azurestorageaccountkey: {{ include "app.storageAccountKey" . | quote }}
{{- end }}
